package com.github.darksoulq.abyssallib.event.custom.server;

import org.bukkit.event.Event;
import org.bukkit.event.HandlerList;
import org.jetbrains.annotations.NotNull;

import java.io.File;

/**
 * Called when a resource pack is generated by AbyssalLib.
 * <p>
 * This event is not cancellable and is fired after the resource pack has been created.
 */
public class ResourcePackGenerateEvent extends Event {

    /**
     * The handler list for this event.
     */
    private static final HandlerList handlers = new HandlerList();

    /**
     * The mod ID that generated the resource pack.
     */
    private final String modid;

    /**
     * The folder containing the generated resource pack contents.
     */
    private final File folder;

    /**
     * The zipped file (if applicable) of the generated resource pack.
     */
    private final File zip;

    /**
     * Constructs a new ResourcePackGenerateEvent.
     *
     * @param modid  The mod ID responsible for the generation.
     * @param folder The folder containing the unzipped resource pack files.
     * @param zip    The zip file of the resource pack (can be null if not zipped).
     */
    public ResourcePackGenerateEvent(String modid, File folder, File zip) {
        this.modid = modid;
        this.folder = folder;
        this.zip = zip;
    }

    /**
     * Gets the mod ID that generated the resource pack.
     *
     * @return The mod ID.
     */
    public String modid() {
        return modid;
    }

    /**
     * Gets the folder containing the resource pack files.
     *
     * @return The folder as a File object.
     */
    public File folder() {
        return folder;
    }

    /**
     * Gets the zipped version of the resource pack file, if applicable.
     *
     * @return The zip file, or null if not zipped.
     */
    public File zip() {
        return zip;
    }

    /**
     * Gets the list of handlers for this event.
     *
     * @return The handler list.
     */
    @Override
    public @NotNull HandlerList getHandlers() {
        return handlers;
    }

    /**
     * Gets the static handler list for this event.
     *
     * @return The handler list.
     */
    public static HandlerList getHandlerList() {
        return handlers;
    }
}
