package com.github.darksoulq.abyssallib.world.data.loot;

import org.bukkit.inventory.ItemStack;

import java.util.ArrayList;
import java.util.List;

/**
 * Represents a full loot table composed of multiple {@link LootPool}s.
 * A loot table is used to generate items based on its defined pools and conditions.
 *
 * <p>Each pool can have its own conditions, rolls, and entries. The loot table
 * itself does not apply any additional filtering—only pools do that.
 */
public class LootTable {
    private final List<LootPool> pools = new ArrayList<>();

    /**
     * Adds a loot pool to this loot table.
     *
     * @param pool the loot pool to add
     * @return this loot table, for method chaining
     */
    public LootTable addPool(LootPool pool) {
        this.pools.add(pool);
        return this;
    }

    /**
     * Generates loot from all eligible pools in this loot table.
     * Each pool is rolled independently, and their results are combined.
     *
     * @param context the loot context to use for generation
     * @return a list of {@link ItemStack}s generated by the loot table
     */
    public List<ItemStack> generate(LootContext context) {
        List<ItemStack> result = new ArrayList<>();
        for (LootPool pool : pools) {
            result.addAll(pool.generate(context));
        }
        return result;
    }
}
