package com.github.darksoulq.abyssallib.world.data.loot;

import com.github.darksoulq.abyssallib.common.serialization.Codec;
import com.github.darksoulq.abyssallib.common.serialization.Codecs;
import com.github.darksoulq.abyssallib.server.registry.Registries;
import org.bukkit.inventory.ItemStack;

/**
 * An abstract base class for functions that modify an {@link ItemStack} generated by a loot table.
 * <p>
 * Functions are applied sequentially to a loot entry. Common uses include setting
 * item amounts, applying enchantments, or modifying display names.
 */
public abstract class LootFunction {

    /**
     * Applies this function's logic to the provided item stack.
     *
     * @param stack   The {@link ItemStack} to be modified.
     * @param context The {@link LootContext} providing environmental data for the application.
     * @return The resulting modified {@link ItemStack}.
     */
    public abstract ItemStack apply(ItemStack stack, LootContext context);

    /**
     * Retrieves the specific type definition associated with this function.
     *
     * @return The {@link LootFunctionType} used for registry identification and serialization.
     */
    public abstract LootFunctionType<?> getType();

    /**
     * Polymorphic codec for serializing and deserializing loot functions.
     * <p>
     * Decodes the function by looking up the "type" field in the {@link Registries#LOOT_FUNCTIONS}
     * and delegating the rest of the object to that specific type's codec.
     */
    public static final Codec<LootFunction> CODEC = Codec.dispatch(
        LootFunction.class,
        "type",
        Codecs.STRING,
        function -> {
            String typeId = Registries.LOOT_FUNCTIONS.getId(function.getType());
            if (typeId == null) {
                throw new IllegalStateException("Unregistered loot function type");
            }
            return typeId;
        },
        typeId -> {
            LootFunctionType<?> type = Registries.LOOT_FUNCTIONS.get(typeId);
            if (type == null) {
                return Codec.error("Unknown loot function: " + typeId);
            }
            return type.codec().unchecked();
        }
    ).describe("LootFunction");
}