name: AbyssalLib
version: '${version}'
main: com.github.darksoulq.abyssallib.AbyssalLib
api-version: '${apiVersion}'
authors: [ DarkSoul ]

folia-supported: true

bootstrapper: com.github.darksoulq.abyssallib.Bootstrap
loader: com.github.darksoulq.abyssallib.Loader

dependencies:
  server:
    ResourcePackManager:
      required: false
      load: BEFORE
    PlaceholderAPI:
      required: false
      load: BEFORE
    TheBrewingProject:
      required: false
      load: BEFORE