name: AbyssalLib
version: '1.1.0'
main: io.github.darksoulq.abyssalLib.AbyssalLib
api-version: '1.21'
authors: [ DarkSoul ]

dependencies:
  server:
    ResourcePackManager:
      required: false
      load: BEFORE