name: AbyssalLib
version: '1.2.3-mc1.21.5'
main: com.github.darksoulq.abyssallib.AbyssalLib
api-version: '1.21'
authors: [ DarkSoul ]

dependencies:
  server:
    ResourcePackManager:
      required: false
      load: BEFORE