name: AbyssalLib
version: '1.5.0-mc1.21.8'
main: com.github.darksoulq.abyssallib.AbyssalLib
api-version: '1.21'
authors: [ DarkSoul ]

bootstrapper: com.github.darksoulq.abyssallib.Bootstrap
loader: com.github.darksoulq.abyssallib.Loader

dependencies:
  server:
    ResourcePackManager:
      required: false
      load: BEFORE
