name: AbyssalLib
version: '1.6.1-mc1.21.9'
main: com.github.darksoulq.abyssallib.AbyssalLib
api-version: '1.21'
authors: [ DarkSoul ]

bootstrapper: com.github.darksoulq.abyssallib.Bootstrap
loader: com.github.darksoulq.abyssallib.Loader

dependencies:
  server:
    ResourcePackManager:
      required: false
      load: BEFORE
    Nexo:
      required: false
      load: BEFORE
