name: AbyssalLib
version: '1.0-SNAPSHOT'
main: me.darksoul.abyssalLib.AbyssalLib
api-version: '1.21'
authors: [ DarkSoul ]

dependencies:
  server:
    ResourcePackManager:
      required: false
      load: BEFORE