package com.github.darksoulq.abyssallib.server.event.custom.server;

import org.bukkit.event.Event;
import org.bukkit.event.HandlerList;
import org.jetbrains.annotations.NotNull;

import java.io.File;

/**
 * Event triggered when a resource pack is generated by AbyssalLib.
 * <p>
 * This event is fired after the resource pack has been fully created and written to disk.
 * It is not cancellable.
 */
public class ResourcePackGenerateEvent extends Event {

    /**
     * Handler list for Bukkit's internal event system.
     */
    private static final HandlerList handlers = new HandlerList();

    /**
     * The mod ID that triggered the resource pack generation.
     */
    private final String modid;

    /**
     * The zipped file representing the generated resource pack.
     */
    private final File zip;

    /**
     * Constructs a new {@code ResourcePackGenerateEvent}.
     *
     * @param modid The mod ID responsible for generating the resource pack.
     * @param zip   The resulting zip file of the generated resource pack.
     */
    public ResourcePackGenerateEvent(@NotNull String modid, @NotNull File zip) {
        this.modid = modid;
        this.zip = zip;
    }

    /**
     * Returns the mod ID that triggered the resource pack generation.
     *
     * @return The mod ID as a {@link String}.
     */
    public @NotNull String modid() {
        return modid;
    }

    /**
     * Returns the zipped resource pack file.
     *
     * @return The generated resource pack as a {@link File}.
     */
    public @NotNull File zip() {
        return zip;
    }

    /**
     * Returns the list of handlers for this event.
     *
     * @return The {@link HandlerList} for this event.
     */
    @Override
    public @NotNull HandlerList getHandlers() {
        return handlers;
    }
}
