package com.github.darksoulq.abyssallib.world.data.loot.function;

import com.github.darksoulq.abyssallib.common.serialization.Codec;
import com.github.darksoulq.abyssallib.common.serialization.Codecs;
import com.github.darksoulq.abyssallib.common.serialization.RecordBuilder;
import com.github.darksoulq.abyssallib.world.data.loot.LootContext;
import com.github.darksoulq.abyssallib.world.data.loot.LootFunction;
import com.github.darksoulq.abyssallib.world.data.loot.LootFunctionType;
import io.papermc.paper.datacomponent.DataComponentType;
import io.papermc.paper.datacomponent.DataComponentTypes;
import io.papermc.paper.datacomponent.item.ItemEnchantments;
import io.papermc.paper.registry.RegistryAccess;
import io.papermc.paper.registry.RegistryKey;
import org.bukkit.Material;
import org.bukkit.NamespacedKey;
import org.bukkit.enchantments.Enchantment;
import org.bukkit.inventory.ItemStack;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * A loot function that applies a random enchantment to the generated item.
 * <p>
 * If a list of enchantments is provided, the function will pick one at random from that list.
 * If the list is empty, it will pick from all enchantments registered in the game that
 * are compatible with the item being enchanted.
 * </p>
 */
@SuppressWarnings("UnstableApiUsage")
public class EnchantRandomlyFunction extends LootFunction {

    /**
     * The codec used for serializing and deserializing this function's configuration.
     */
    public static final Codec<EnchantRandomlyFunction> CODEC = RecordBuilder.create(instance -> instance.group(
        Codecs.STRING.list().optionalFieldOf("enchantments", Collections.emptyList()).forGetter(EnchantRandomlyFunction.class, p -> p.enchantments)
    ).apply(instance, EnchantRandomlyFunction::new)).describe("EnchantRandomlyFunction");

    /**
     * The registered type definition for this loot function.
     */
    public static final LootFunctionType<EnchantRandomlyFunction> TYPE = () -> CODEC;

    /**
     * The list of potential enchantment IDs to choose from.
     */
    private final List<String> enchantments;

    /**
     * Constructs a new EnchantRandomlyFunction.
     *
     * @param enchantments A list of {@link NamespacedKey} strings representing valid enchantments.
     */
    public EnchantRandomlyFunction(List<String> enchantments) {
        this.enchantments = enchantments;
    }

    /**
     * Applies a random enchantment to the provided {@link ItemStack}.
     * <p>
     * This method handles both standard items (using {@link DataComponentTypes#ENCHANTMENTS})
     * and enchanted books (using {@link DataComponentTypes#STORED_ENCHANTMENTS}).
     * It randomly selects a level between 1 and the enchantment's max level.
     * </p>
     *
     * @param stack   The {@link ItemStack} generated by the loot pool.
     * @param context The {@link LootContext} providing the random source and environmental data.
     * @return The modified {@link ItemStack} with a new enchantment applied.
     */
    @Override
    public ItemStack apply(ItemStack stack, LootContext context) {
        Enchantment enchantment;
        if (enchantments.isEmpty()) {
            List<Enchantment> all = new ArrayList<>();
            for (Enchantment e : RegistryAccess.registryAccess().getRegistry(RegistryKey.ENCHANTMENT)) {
                if (e.canEnchantItem(stack)) all.add(e);
            }
            if (all.isEmpty()) return stack;
            enchantment = all.get(context.random().nextInt(all.size()));
        } else {
            String key = enchantments.get(context.random().nextInt(enchantments.size()));
            enchantment = RegistryAccess.registryAccess().getRegistry(RegistryKey.ENCHANTMENT).get(NamespacedKey.fromString(key));
        }

        if (enchantment == null) return stack;

        int level = context.random().nextInt(enchantment.getMaxLevel()) + 1;

        DataComponentType.Valued<ItemEnchantments> type = stack.getType() == Material.ENCHANTED_BOOK
            ? DataComponentTypes.STORED_ENCHANTMENTS
            : DataComponentTypes.ENCHANTMENTS;

        ItemEnchantments current = stack.getData(type);
        if (current == null) current = ItemEnchantments.itemEnchantments().build();

        ItemEnchantments.Builder builder = ItemEnchantments.itemEnchantments();
        builder.addAll(current.enchantments());

        stack.setData(type, builder.add(enchantment, level).build());
        return stack;
    }

    /**
     * @return The {@link LootFunctionType} associated with this function.
     */
    @Override
    public LootFunctionType<?> getType() {
        return TYPE;
    }
}