package com.github.darksoulq.abyssallib.world.data.loot.function;

import com.github.darksoulq.abyssallib.common.serialization.Codec;
import com.github.darksoulq.abyssallib.common.serialization.DynamicOps;
import com.github.darksoulq.abyssallib.world.data.loot.LootContext;
import com.github.darksoulq.abyssallib.world.data.loot.LootFunction;
import com.github.darksoulq.abyssallib.world.data.loot.LootFunctionType;
import org.bukkit.inventory.ItemStack;

import java.util.Collections;
import java.util.Random;

/**
 * A loot function that reduces the amount of items in a stack based on an explosion decay algorithm.
 * <p>
 * This function simulates the destruction of loot that occurs when a block is broken by an explosion,
 * where each individual item in the stack has a probability of being "destroyed" and removed.
 * </p>
 */
public class ExplosionDecayFunction extends LootFunction {

    /**
     * The codec used for serializing and deserializing the explosion decay function.
     * <p>
     * Since this function maintains no state or configuration parameters, it decodes
     * from and encodes to an empty map structure.
     * </p>
     */
    public static final Codec<ExplosionDecayFunction> CODEC = new Codec<>() {
        /**
         * Decodes an ExplosionDecayFunction instance.
         * * @param ops   The {@link DynamicOps} logic.
         * @param input The serialized input.
         * @param <D>   The data format type.
         * @return A new instance of {@link ExplosionDecayFunction}.
         */
        @Override
        public <D> ExplosionDecayFunction decode(DynamicOps<D> ops, D input) {
            return new ExplosionDecayFunction();
        }

        /**
         * Encodes an ExplosionDecayFunction instance into an empty map.
         * * @param ops   The {@link DynamicOps} logic.
         * @param value The function instance to encode.
         * @param <D>   The data format type.
         * @return An empty map representation.
         */
        @Override
        public <D> D encode(DynamicOps<D> ops, ExplosionDecayFunction value) {
            return ops.createMap(Collections.emptyMap());
        }
    };

    /**
     * The registered type definition for this loot function.
     */
    public static final LootFunctionType<ExplosionDecayFunction> TYPE = () -> CODEC;

    /**
     * Applies the explosion decay logic to the provided {@link ItemStack}.
     * <p>
     * Each item in the original stack is subjected to a random roll against a decay
     * threshold derived from the context's random source. Items that fail the roll
     * are discarded, and the stack's final amount is updated to the remaining count.
     * </p>
     * * @param stack   The {@link ItemStack} generated by the loot entry.
     * @param context The {@link LootContext} providing the random source and environmental data.
     * @return The modified {@link ItemStack} with the updated (and potentially reduced) amount.
     */
    @Override
    public ItemStack apply(ItemStack stack, LootContext context) {
        Random random = context.random();
        float decay = 1.0f / random.nextFloat();
        int amount = stack.getAmount();
        int result = 0;
        for (int i = 0; i < amount; i++) {
            if (random.nextFloat() <= decay) {
                result++;
            }
        }
        stack.setAmount(result);
        return stack;
    }

    /**
     * Retrieves the specific type definition for this loot function.
     * * @return The {@link LootFunctionType} associated with {@link ExplosionDecayFunction}.
     */
    @Override
    public LootFunctionType<?> getType() {
        return TYPE;
    }
}