package com.github.darksoulq.abyssallib.world.data.loot.function;

import com.github.darksoulq.abyssallib.common.serialization.Codec;
import com.github.darksoulq.abyssallib.common.serialization.DynamicOps;
import com.github.darksoulq.abyssallib.world.data.loot.LootContext;
import com.github.darksoulq.abyssallib.world.data.loot.LootFunction;
import com.github.darksoulq.abyssallib.world.data.loot.LootFunctionType;
import org.bukkit.Bukkit;
import org.bukkit.inventory.FurnaceRecipe;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.Recipe;

import java.util.Collections;
import java.util.Iterator;

/**
 * A loot function that attempts to smelt the generated item stack.
 * <p>
 * This function iterates through the server's recipe registry to find a
 * {@link FurnaceRecipe} that accepts the current item as an input. If a
 * match is found, the item is replaced with the smelting result while
 * maintaining the original stack size.
 * </p>
 */
public class FurnaceSmeltFunction extends LootFunction {

    /**
     * The codec used for serializing and deserializing the furnace smelt function.
     * <p>
     * As this function logic is procedural and carries no unique configuration
     * state, it encodes to and decodes from an empty map structure.
     * </p>
     */
    public static final Codec<FurnaceSmeltFunction> CODEC = new Codec<>() {
        /**
         * Decodes a FurnaceSmeltFunction instance.
         * * @param ops   The {@link DynamicOps} instance defining the data format.
         * @param input The serialized input data.
         * @param <D>   The type of the data being processed.
         * @return A new instance of {@link FurnaceSmeltFunction}.
         */
        @Override
        public <D> FurnaceSmeltFunction decode(DynamicOps<D> ops, D input) {
            return new FurnaceSmeltFunction();
        }

        /**
         * Encodes the FurnaceSmeltFunction instance.
         * * @param ops   The {@link DynamicOps} instance defining the data format.
         * @param value The function instance to encode.
         * @param <D>   The type of the data being processed.
         * @return An empty map representing the encoded state.
         */
        @Override
        public <D> D encode(DynamicOps<D> ops, FurnaceSmeltFunction value) {
            return ops.createMap(Collections.emptyMap());
        }
    };

    /**
     * The registered type definition for the furnace smelt loot function.
     */
    public static final LootFunctionType<FurnaceSmeltFunction> TYPE = () -> CODEC;

    /**
     * Applies the smelting transformation to the generated {@link ItemStack}.
     * <p>
     * Scans the global {@link Bukkit#recipeIterator()} for a {@link FurnaceRecipe}.
     * If the input material of a recipe matches the material of the provided stack,
     * the stack is transformed into the recipe result.
     * </p>
     * * @param stack   The {@link ItemStack} generated by the loot entry.
     * @param context The {@link LootContext} providing environmental data.
     * @return The smelted {@link ItemStack} if a recipe exists; otherwise, the original stack.
     */
    @Override
    public ItemStack apply(ItemStack stack, LootContext context) {
        Iterator<Recipe> iter = Bukkit.recipeIterator();
        while (iter.hasNext()) {
            Recipe r = iter.next();
            if (!(r instanceof FurnaceRecipe fr)) return stack;
            if (fr.getInputChoice().test(stack)) {
                ItemStack result = fr.getResult().clone();
                result.setAmount(stack.getAmount());
                return result;
            }
        }
        return stack;
    }

    /**
     * Retrieves the specific type definition for this loot function.
     * * @return The {@link LootFunctionType} associated with {@link FurnaceSmeltFunction}.
     */
    @Override
    public LootFunctionType<?> getType() {
        return TYPE;
    }
}