package com.github.darksoulq.abyssallib.world.data.loot.function;

import com.github.darksoulq.abyssallib.common.serialization.Codec;
import com.github.darksoulq.abyssallib.common.serialization.Codecs;
import com.github.darksoulq.abyssallib.common.serialization.RecordBuilder;
import com.github.darksoulq.abyssallib.world.data.loot.LootContext;
import com.github.darksoulq.abyssallib.world.data.loot.LootFunction;
import com.github.darksoulq.abyssallib.world.data.loot.LootFunctionType;
import org.bukkit.inventory.ItemStack;

/**
 * A loot function that clamps the stack size of a generated item within a specified minimum and maximum range.
 * <p>
 * This function is useful for ensuring that randomized loot amounts (generated by previous functions
 * like {@code SetCountFunction}) do not exceed or fall below certain balanced thresholds.
 * </p>
 */
public class LimitCountFunction extends LootFunction {

    /**
     * The codec used for serializing and deserializing the limit count function.
     * <p>
     * It maps the "min" and "max" integer fields. If missing, "min" defaults to 0
     * and "max" defaults to {@link Integer#MAX_VALUE}.
     * </p>
     */
    public static final Codec<LimitCountFunction> CODEC = RecordBuilder.create(instance -> instance.group(
        Codecs.INT.optionalFieldOf("min", 0).forGetter(LimitCountFunction.class, p -> p.min),
        Codecs.INT.optionalFieldOf("max", Integer.MAX_VALUE).forGetter(LimitCountFunction.class, p -> p.max)
    ).apply(instance, LimitCountFunction::new)).describe("LimitCountFunction");

    /**
     * The registered type definition for the limit count loot function.
     */
    public static final LootFunctionType<LimitCountFunction> TYPE = () -> CODEC;

    /** The minimum allowable stack size. */
    private final int min;
    /** The maximum allowable stack size. */
    private final int max;

    /**
     * Constructs a new LimitCountFunction with specific bounds.
     *
     * @param min The inclusive minimum amount.
     * @param max The inclusive maximum amount.
     */
    public LimitCountFunction(int min, int max) {
        this.min = min;
        this.max = max;
    }

    /**
     * Applies the clamping logic to the provided {@link ItemStack}.
     * <p>
     * The method retrieves the current stack amount and constrains it such that
     * {@code min <= amount <= max}.
     * </p>
     * * @param stack   The {@link ItemStack} generated by the loot entry.
     * @param context The {@link LootContext} providing environmental data.
     * @return The modified {@link ItemStack} with its amount clamped to the defined range.
     */
    @Override
    public ItemStack apply(ItemStack stack, LootContext context) {
        int count = stack.getAmount();
        stack.setAmount(Math.max(min, Math.min(max, count)));
        return stack;
    }

    /**
     * Retrieves the specific type definition for this loot function.
     * * @return The {@link LootFunctionType} associated with {@link LimitCountFunction}.
     */
    @Override
    public LootFunctionType<?> getType() {
        return TYPE;
    }
}