package com.github.darksoulq.abyssallib.world.data.loot.function;

import com.github.darksoulq.abyssallib.common.serialization.Codec;
import com.github.darksoulq.abyssallib.common.serialization.Codecs;
import com.github.darksoulq.abyssallib.common.serialization.DynamicOps;
import com.github.darksoulq.abyssallib.world.data.loot.LootContext;
import com.github.darksoulq.abyssallib.world.data.loot.LootFunction;
import com.github.darksoulq.abyssallib.world.data.loot.LootFunctionType;
import org.bukkit.enchantments.Enchantment;
import org.bukkit.inventory.ItemStack;

import java.util.HashMap;
import java.util.Map;

/**
 * A loot function that increases the stack size of generated loot based on the Looting enchantment level.
 * <p>
 * This function checks the tool used by the killer in the {@link LootContext}. If the tool has
 * the {@link Enchantment#LOOTING} enchantment, a random bonus amount (between 0 and the enchantment level)
 * is added to the stack size, up to a defined limit.
 * </p>
 */
public class LootingEnchantFunction extends LootFunction {

    /**
     * The codec used for serializing and deserializing the looting enchantment function.
     * <p>
     * It maps the "limit" integer field, which defines the maximum stack size allowed
     * after applying the looting bonus.
     * </p>
     */
    public static final Codec<LootingEnchantFunction> CODEC = new Codec<>() {
        /**
         * Decodes a LootingEnchantFunction instance from the provided serialized data.
         *
         * @param ops   The {@link DynamicOps} instance defining the data format.
         * @param input The serialized input data.
         * @param <D>   The type of the data being processed.
         * @return A new instance of {@link LootingEnchantFunction}.
         * @throws CodecException If the input is not a valid map structure.
         */
        @Override
        public <D> LootingEnchantFunction decode(DynamicOps<D> ops, D input) throws CodecException {
            Map<D, D> map = ops.getMap(input).orElseThrow(() -> new CodecException("Expected map"));
            int limit = Codecs.INT.orElse(0).decode(ops, map.get(ops.createString("limit")));
            return new LootingEnchantFunction(limit);
        }

        /**
         * Encodes the LootingEnchantFunction instance into a serialized format.
         *
         * @param ops   The {@link DynamicOps} instance defining the data format.
         * @param value The function instance to encode.
         * @param <D>   The type of the data being processed.
         * @return A map representing the encoded limit value.
         * @throws CodecException If the encoding process fails.
         */
        @Override
        public <D> D encode(DynamicOps<D> ops, LootingEnchantFunction value) throws CodecException {
            Map<D, D> map = new HashMap<>();
            map.put(ops.createString("limit"), Codecs.INT.encode(ops, value.limit));
            return ops.createMap(map);
        }
    };

    /**
     * The registered type definition for the looting enchantment loot function.
     */
    public static final LootFunctionType<LootingEnchantFunction> TYPE = () -> CODEC;

    /** The maximum stack size allowed after applying the bonus. */
    private final int limit;

    /**
     * Constructs a new LootingEnchantFunction with a specific stack size limit.
     *
     * @param limit The maximum amount an item stack can reach via this function.
     * If 0 or less, defaults to 64.
     */
    public LootingEnchantFunction(int limit) {
        this.limit = limit;
    }

    /**
     * Applies the looting enchantment bonus to the provided {@link ItemStack}.
     * <p>
     * The function requires a valid killer and a tool in the {@link LootContext}.
     * A random integer between 0 and the Looting level (inclusive) is added to the
     * current stack amount, constrained by the {@link #limit}.
     * </p>
     *
     * @param stack   The {@link ItemStack} generated by the loot entry.
     * @param context The {@link LootContext} providing the killer, tool, and random source.
     * @return The modified {@link ItemStack} with its amount potentially increased by looting.
     */
    @Override
    public ItemStack apply(ItemStack stack, LootContext context) {
        if (context.killer() == null) return stack;
        ItemStack tool = context.tool();
        if (tool != null) {
            int level = tool.getEnchantmentLevel(Enchantment.LOOTING);
            if (level > 0) {
                int bonus = context.random().nextInt(level + 1);
                stack.setAmount(Math.min(limit > 0 ? limit : 64, stack.getAmount() + bonus));
            }
        }
        return stack;
    }

    /**
     * Retrieves the specific type definition for this loot function.
     *
     * @return The {@link LootFunctionType} associated with {@link LootingEnchantFunction}.
     */
    @Override
    public LootFunctionType<?> getType() {
        return TYPE;
    }
}