package com.github.darksoulq.abyssallib.world.data.loot.function;

import com.github.darksoulq.abyssallib.common.serialization.Codec;
import com.github.darksoulq.abyssallib.common.serialization.Codecs;
import com.github.darksoulq.abyssallib.common.serialization.RecordBuilder;
import com.github.darksoulq.abyssallib.world.data.loot.LootContext;
import com.github.darksoulq.abyssallib.world.data.loot.LootFunction;
import com.github.darksoulq.abyssallib.world.data.loot.LootFunctionType;
import org.bukkit.enchantments.Enchantment;
import org.bukkit.inventory.ItemStack;

/**
 * A loot function that increases the stack size of generated loot based on the Looting enchantment level.
 * <p>
 * This function checks the tool used by the killer in the {@link LootContext}. If the tool has
 * the {@link Enchantment#LOOTING} enchantment, a random bonus amount (between 0 and the enchantment level)
 * is added to the stack size, up to a defined limit.
 * </p>
 */
public class LootingEnchantFunction extends LootFunction {

    /**
     * The codec used for serializing and deserializing the looting enchantment function.
     * <p>
     * It maps the "limit" integer field, which defines the maximum stack size allowed
     * after applying the looting bonus.
     * </p>
     */
    public static final Codec<LootingEnchantFunction> CODEC = RecordBuilder.create(instance -> instance.group(
        Codecs.INT.optionalFieldOf("limit", 0).forGetter(LootingEnchantFunction.class, p -> p.limit)
    ).apply(instance, LootingEnchantFunction::new)).describe("LootingEnchantFunction");

    /**
     * The registered type definition for the looting enchantment loot function.
     */
    public static final LootFunctionType<LootingEnchantFunction> TYPE = () -> CODEC;

    /** The maximum stack size allowed after applying the bonus. */
    private final int limit;

    /**
     * Constructs a new LootingEnchantFunction with a specific stack size limit.
     *
     * @param limit The maximum amount an item stack can reach via this function.
     * If 0 or less, defaults to 64.
     */
    public LootingEnchantFunction(int limit) {
        this.limit = limit;
    }

    /**
     * Applies the looting enchantment bonus to the provided {@link ItemStack}.
     * <p>
     * The function requires a valid killer and a tool in the {@link LootContext}.
     * A random integer between 0 and the Looting level (inclusive) is added to the
     * current stack amount, constrained by the {@link #limit}.
     * </p>
     *
     * @param stack   The {@link ItemStack} generated by the loot entry.
     * @param context The {@link LootContext} providing the killer, tool, and random source.
     * @return The modified {@link ItemStack} with its amount potentially increased by looting.
     */
    @Override
    public ItemStack apply(ItemStack stack, LootContext context) {
        if (context.killer() == null) return stack;
        ItemStack tool = context.tool();
        if (tool != null) {
            int level = tool.getEnchantmentLevel(Enchantment.LOOTING);
            if (level > 0) {
                int bonus = context.random().nextInt(level + 1);
                stack.setAmount(Math.min(limit > 0 ? limit : 64, stack.getAmount() + bonus));
            }
        }
        return stack;
    }

    /**
     * Retrieves the specific type definition for this loot function.
     *
     * @return The {@link LootFunctionType} associated with {@link LootingEnchantFunction}.
     */
    @Override
    public LootFunctionType<?> getType() {
        return TYPE;
    }
}