package com.github.darksoulq.abyssallib.world.data.loot.function;

import com.github.darksoulq.abyssallib.common.serialization.Codec;
import com.github.darksoulq.abyssallib.common.serialization.Codecs;
import com.github.darksoulq.abyssallib.common.serialization.RecordBuilder;
import com.github.darksoulq.abyssallib.world.data.loot.LootContext;
import com.github.darksoulq.abyssallib.world.data.loot.LootFunction;
import com.github.darksoulq.abyssallib.world.data.loot.LootFunctionType;
import org.bukkit.inventory.ItemStack;

/**
 * A loot function that modifies the stack size of a generated item to a random value within a specified range.
 * <p>
 * This is the standard function used to provide variety in loot drops, allowing a single
 * loot entry to represent a quantity range (e.g., 1-3 diamonds) rather than a fixed amount.
 * </p>
 */
public class SetCountFunction extends LootFunction {

    /**
     * The codec used for serializing and deserializing the set count function.
     * <p>
     * It requires "min" and "max" integer fields to define the inclusive range
     * for the random generation.
     * </p>
     */
    public static final Codec<SetCountFunction> CODEC = RecordBuilder.create(instance -> instance.group(
        Codecs.INT.fieldOf("min").forGetter(SetCountFunction.class, p -> p.min),
        Codecs.INT.fieldOf("max").forGetter(SetCountFunction.class, p -> p.max)
    ).apply(instance, SetCountFunction::new)).describe("SetCountFunction");

    /**
     * The registered type definition for the set count loot function.
     */
    public static final LootFunctionType<SetCountFunction> TYPE = () -> CODEC;

    /**
     * The inclusive minimum stack size.
     */
    private final int min;
    /**
     * The inclusive maximum stack size.
     */
    private final int max;

    /**
     * Constructs a new SetCountFunction with a specified range.
     *
     * @param min The minimum possible stack size (inclusive).
     * @param max The maximum possible stack size (inclusive).
     */
    public SetCountFunction(int min, int max) {
        this.min = min;
        this.max = max;
    }

    /**
     * Randomizes the amount of the provided {@link ItemStack} based on the defined range.
     * <p>
     * The new amount is calculated using the {@link java.util.Random} instance
     * provided by the {@link LootContext}.
     * </p>
     *
     * @param stack   The {@link ItemStack} generated by the loot entry.
     * @param context The {@link LootContext} providing the random source.
     * @return The modified {@link ItemStack} with its new randomized amount.
     */
    @Override
    public ItemStack apply(ItemStack stack, LootContext context) {
        stack.setAmount(context.random().nextInt(max - min + 1) + min);
        return stack;
    }

    /**
     * Retrieves the specific type definition for this loot function.
     *
     * @return The {@link LootFunctionType} associated with {@link SetCountFunction}.
     */
    @Override
    public LootFunctionType<?> getType() {
        return TYPE;
    }
}