package com.github.darksoulq.abyssallib.world.data.loot.function;

import com.github.darksoulq.abyssallib.common.serialization.Codec;
import com.github.darksoulq.abyssallib.common.serialization.Codecs;
import com.github.darksoulq.abyssallib.common.serialization.DynamicOps;
import com.github.darksoulq.abyssallib.world.data.loot.LootContext;
import com.github.darksoulq.abyssallib.world.data.loot.LootFunction;
import com.github.darksoulq.abyssallib.world.data.loot.LootFunctionType;
import io.papermc.paper.datacomponent.DataComponentTypes;
import org.bukkit.inventory.ItemStack;

import java.util.HashMap;
import java.util.Map;

/**
 * A loot function that sets the damage (durability loss) of a generated item based on a percentage range.
 * <p>
 * The damage is calculated as a percentage of the item's maximum durability. For example,
 * a range of 0.1 to 0.5 would result in an item missing 10% to 50% of its total durability.
 * </p>
 */
public class SetDamageFunction extends LootFunction {

    /**
     * The codec used for serializing and deserializing the set damage function.
     * <p>
     * It requires "min" and "max" float fields representing the damage percentage range (0.0 to 1.0).
     * </p>
     */
    public static final Codec<SetDamageFunction> CODEC = new Codec<>() {
        /**
         * Decodes a SetDamageFunction instance from the provided serialized data.
         *
         * @param ops   The {@link DynamicOps} instance defining the data format.
         * @param input The serialized input data.
         * @param <D>   The type of the data being processed.
         * @return A new instance of {@link SetDamageFunction}.
         * @throws CodecException If "min" or "max" fields are missing or invalid.
         */
        @Override
        public <D> SetDamageFunction decode(DynamicOps<D> ops, D input) throws CodecException {
            Map<D, D> map = ops.getMap(input).orElseThrow(() -> new CodecException("Expected map"));
            float min = Codecs.FLOAT.decode(ops, map.get(ops.createString("min")));
            float max = Codecs.FLOAT.decode(ops, map.get(ops.createString("max")));
            return new SetDamageFunction(min, max);
        }

        /**
         * Encodes the SetDamageFunction instance into a serialized format.
         *
         * @param ops   The {@link DynamicOps} instance defining the data format.
         * @param value The function instance to encode.
         * @param <D>   The type of the data being processed.
         * @return A map representing the encoded min and max damage percentages.
         * @throws CodecException If the encoding process fails.
         */
        @Override
        public <D> D encode(DynamicOps<D> ops, SetDamageFunction value) throws CodecException {
            Map<D, D> map = new HashMap<>();
            map.put(ops.createString("min"), Codecs.FLOAT.encode(ops, value.min));
            map.put(ops.createString("max"), Codecs.FLOAT.encode(ops, value.max));
            return ops.createMap(map);
        }
    };

    /**
     * The registered type definition for the set damage loot function.
     */
    public static final LootFunctionType<SetDamageFunction> TYPE = () -> CODEC;

    /** The minimum damage percentage (inclusive). */
    private final float min;
    /** The maximum damage percentage (inclusive). */
    private final float max;

    /**
     * Constructs a new SetDamageFunction.
     *
     * @param min The minimum damage percentage (0.0 - 1.0).
     * @param max The maximum damage percentage (0.0 - 1.0).
     */
    public SetDamageFunction(float min, float max) {
        this.min = min;
        this.max = max;
    }

    /**
     * Applies the randomized damage to the provided {@link ItemStack}.
     * <p>
     * This method calculates the damage based on either the material's default maximum durability
     * or the value defined in the {@link DataComponentTypes#MAX_DAMAGE} component if present.
     * </p>
     *
     * @param stack   The {@link ItemStack} generated by the loot entry.
     * @param context The {@link LootContext} providing the random source.
     * @return The modified {@link ItemStack} with the randomized damage value applied.
     */
    @Override
    public ItemStack apply(ItemStack stack, LootContext context) {
        float damagePercent = min + (max - min) * context.random().nextFloat();
        int maxDurability = stack.getType().getMaxDurability();
        Integer maxDamage = stack.getData(DataComponentTypes.MAX_DAMAGE);
        if (maxDamage != null) maxDurability = maxDamage;
        stack.setData(DataComponentTypes.DAMAGE, (int)(maxDurability * damagePercent));
        return stack;
    }

    /**
     * Retrieves the specific type definition for this loot function.
     *
     * @return The {@link LootFunctionType} associated with {@link SetDamageFunction}.
     */
    @Override
    public LootFunctionType<?> getType() {
        return TYPE;
    }
}