package com.github.darksoulq.abyssallib.world.data.loot.function;

import com.github.darksoulq.abyssallib.common.serialization.Codec;
import com.github.darksoulq.abyssallib.common.serialization.Codecs;
import com.github.darksoulq.abyssallib.common.serialization.RecordBuilder;
import com.github.darksoulq.abyssallib.world.data.loot.LootContext;
import com.github.darksoulq.abyssallib.world.data.loot.LootFunction;
import com.github.darksoulq.abyssallib.world.data.loot.LootFunctionType;
import io.papermc.paper.datacomponent.DataComponentTypes;
import io.papermc.paper.datacomponent.item.ItemLore;
import net.kyori.adventure.text.Component;
import org.bukkit.inventory.ItemStack;

import java.util.List;

/**
 * A loot function that overrides the lore (description) of a generated item.
 * <p>
 * This function utilizes Adventure {@link Component}s to support modern text formatting,
 * including RGB colors, gradients, and translatable strings. The lore is applied via
 * the {@link DataComponentTypes#LORE} data component.
 * </p>
 */
public class SetLoreFunction extends LootFunction {

    /**
     * The codec used for serializing and deserializing the set lore function.
     * <p>
     * It expects a "lore" field containing a list of serialized text components.
     * </p>
     */
    public static final Codec<SetLoreFunction> CODEC = RecordBuilder.create(instance -> instance.group(
        Codecs.TEXT_COMPONENT.list().fieldOf("lore").forGetter(SetLoreFunction.class, p -> p.lore)
    ).apply(instance, SetLoreFunction::new)).describe("SetLoreFunction");

    /**
     * The registered type definition for the set lore loot function.
     */
    public static final LootFunctionType<SetLoreFunction> TYPE = () -> CODEC;

    /** The list of text components to be applied as lore. */
    private final List<Component> lore;

    /**
     * Constructs a new SetLoreFunction with the specified lore lines.
     *
     * @param lore A {@link List} of Adventure {@link Component}s.
     */
    public SetLoreFunction(List<Component> lore) {
        this.lore = lore;
    }

    /**
     * Applies the configured lore to the provided {@link ItemStack}.
     * <p>
     * This method wraps the component list into an {@link ItemLore} instance and
     * sets it as the item's lore data component.
     * </p>
     *
     * @param stack   The {@link ItemStack} generated by the loot entry.
     * @param context The {@link LootContext} providing environmental data.
     * @return The modified {@link ItemStack} with the new lore applied.
     */
    @Override
    public ItemStack apply(ItemStack stack, LootContext context) {
        stack.setData(DataComponentTypes.LORE, ItemLore.lore(lore));
        return stack;
    }

    /**
     * Retrieves the specific type definition for this loot function.
     *
     * @return The {@link LootFunctionType} associated with {@link SetLoreFunction}.
     */
    @Override
    public LootFunctionType<?> getType() {
        return TYPE;
    }
}