package com.github.darksoulq.abyssallib.world.data.loot.function;

import com.github.darksoulq.abyssallib.common.serialization.Codec;
import com.github.darksoulq.abyssallib.common.serialization.Codecs;
import com.github.darksoulq.abyssallib.common.serialization.DynamicOps;
import com.github.darksoulq.abyssallib.world.data.loot.LootContext;
import com.github.darksoulq.abyssallib.world.data.loot.LootFunction;
import com.github.darksoulq.abyssallib.world.data.loot.LootFunctionType;
import io.papermc.paper.datacomponent.DataComponentTypes;
import io.papermc.paper.datacomponent.item.ItemLore;
import net.kyori.adventure.text.Component;
import org.bukkit.inventory.ItemStack;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * A loot function that overrides the lore (description) of a generated item.
 * <p>
 * This function utilizes Adventure {@link Component}s to support modern text formatting,
 * including RGB colors, gradients, and translatable strings. The lore is applied via
 * the {@link DataComponentTypes#LORE} data component.
 * </p>
 */
public class SetLoreFunction extends LootFunction {

    /**
     * The codec used for serializing and deserializing the set lore function.
     * <p>
     * It expects a "lore" field containing a list of serialized text components.
     * </p>
     */
    public static final Codec<SetLoreFunction> CODEC = new Codec<>() {
        /**
         * Decodes a SetLoreFunction instance from the provided serialized data.
         *
         * @param ops   The {@link DynamicOps} instance defining the data format.
         * @param input The serialized input data.
         * @param <D>   The type of the data being processed.
         * @return A new instance of {@link SetLoreFunction}.
         * @throws CodecException If the "lore" field is missing or components are invalid.
         */
        @Override
        public <D> SetLoreFunction decode(DynamicOps<D> ops, D input) throws CodecException {
            Map<D, D> map = ops.getMap(input).orElseThrow(() -> new CodecException("Expected map"));
            List<Component> lore = Codecs.TEXT_COMPONENT.list().decode(ops, map.get(ops.createString("lore")));
            return new SetLoreFunction(lore);
        }

        /**
         * Encodes the SetLoreFunction instance into a serialized format.
         *
         * @param ops   The {@link DynamicOps} instance defining the data format.
         * @param value The function instance to encode.
         * @param <D>   The type of the data being processed.
         * @return A map representing the encoded lore components.
         * @throws CodecException If the encoding process fails.
         */
        @Override
        public <D> D encode(DynamicOps<D> ops, SetLoreFunction value) throws CodecException {
            Map<D, D> map = new HashMap<>();
            map.put(ops.createString("lore"), Codecs.TEXT_COMPONENT.list().encode(ops, value.lore));
            return ops.createMap(map);
        }
    };

    /**
     * The registered type definition for the set lore loot function.
     */
    public static final LootFunctionType<SetLoreFunction> TYPE = () -> CODEC;

    /** The list of text components to be applied as lore. */
    private final List<Component> lore;

    /**
     * Constructs a new SetLoreFunction with the specified lore lines.
     *
     * @param lore A {@link List} of Adventure {@link Component}s.
     */
    public SetLoreFunction(List<Component> lore) {
        this.lore = lore;
    }

    /**
     * Applies the configured lore to the provided {@link ItemStack}.
     * <p>
     * This method wraps the component list into an {@link ItemLore} instance and
     * sets it as the item's lore data component.
     * </p>
     *
     * @param stack   The {@link ItemStack} generated by the loot entry.
     * @param context The {@link LootContext} providing environmental data.
     * @return The modified {@link ItemStack} with the new lore applied.
     */
    @Override
    public ItemStack apply(ItemStack stack, LootContext context) {
        stack.setData(DataComponentTypes.LORE, ItemLore.lore(lore));
        return stack;
    }

    /**
     * Retrieves the specific type definition for this loot function.
     *
     * @return The {@link LootFunctionType} associated with {@link SetLoreFunction}.
     */
    @Override
    public LootFunctionType<?> getType() {
        return TYPE;
    }
}