package com.github.darksoulq.abyssallib.world.data.loot.function;

import com.github.darksoulq.abyssallib.common.serialization.Codec;
import com.github.darksoulq.abyssallib.common.serialization.Codecs;
import com.github.darksoulq.abyssallib.common.serialization.RecordBuilder;
import com.github.darksoulq.abyssallib.world.data.loot.LootContext;
import com.github.darksoulq.abyssallib.world.data.loot.LootFunction;
import com.github.darksoulq.abyssallib.world.data.loot.LootFunctionType;
import io.papermc.paper.datacomponent.DataComponentTypes;
import net.kyori.adventure.text.Component;
import org.bukkit.inventory.ItemStack;

/**
 * A loot function that overrides the custom display name of a generated item.
 * <p>
 * This function applies a {@link Component} to the {@link DataComponentTypes#CUSTOM_NAME}
 * component type, allowing for full Adventure text support including colors,
 * styling, and translatable components.
 * </p>
 */
public class SetNameFunction extends LootFunction {

    /**
     * The codec used for serializing and deserializing the set name function.
     * <p>
     * It maps the "name" field to a serialized Adventure {@link Component}.
     * </p>
     */
    public static final Codec<SetNameFunction> CODEC = RecordBuilder.create(instance -> instance.group(
        Codecs.TEXT_COMPONENT.fieldOf("name").forGetter(SetNameFunction.class, p -> p.name)
    ).apply(instance, SetNameFunction::new)).describe("SetNameFunction");

    /**
     * The registered type definition for the set name loot function.
     */
    public static final LootFunctionType<SetNameFunction> TYPE = () -> CODEC;

    /**
     * The Adventure {@link Component} to be applied as the item name.
     */
    private final Component name;

    /**
     * Constructs a new SetNameFunction with a specific component.
     *
     * @param name The {@link Component} to use as the item's custom name.
     */
    public SetNameFunction(Component name) {
        this.name = name;
    }

    /**
     * Applies the custom name to the provided {@link ItemStack}.
     * <p>
     * This method directly sets the {@link DataComponentTypes#CUSTOM_NAME} data
     * on the stack using the configured component.
     * </p>
     *
     * @param stack   The {@link ItemStack} generated by the loot entry.
     * @param context The {@link LootContext} providing environmental data.
     * @return The modified {@link ItemStack} with the new custom name applied.
     */
    @Override
    public ItemStack apply(ItemStack stack, LootContext context) {
        stack.setData(DataComponentTypes.CUSTOM_NAME, name);
        return stack;
    }

    /**
     * Retrieves the specific type definition for this loot function.
     *
     * @return The {@link LootFunctionType} associated with {@link SetNameFunction}.
     */
    @Override
    public LootFunctionType<?> getType() {
        return TYPE;
    }
}