name: Repository Notifications

on:
  push:
    branches: ["**"]
  pull_request:
    types: [opened, closed, reopened, merged]
  issues:
    types: [opened, closed, reopened]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  watch:
    types: [started]
  fork:

jobs:
  push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Build Push Embed JSON
        run: |
          REPO="${GITHUB_REPOSITORY}"
          REF="${GITHUB_REF_NAME}"
          ACTOR="${GITHUB_ACTOR}"
          COMPARE="${GITHUB_EVENT_COMPARE}"
          COMMITS_JSON="${GITHUB_EVENT_COMMITS}"

          MAX_COMMITS=5
          COMMITS_FIELDS="[]"
          COUNT=0
          TOTAL=$(jq 'length' <<< "$COMMITS_JSON")

          for row in $(echo "$COMMITS_JSON" | jq -r '.[].id'); do
            COUNT=$((COUNT+1))
            MSG=$(jq -r ".[] | select(.id | startswith(\"$row\")) | .message" <<< "$COMMITS_JSON")
            TITLE=$(echo "$MSG" | head -n1)
            BODY=$(echo "$MSG" | tail -n +2)
            if [ -n "$BODY" ]; then
              BODY=$(echo "$BODY" | tr '\n' ' ' | cut -c1-200)
              BODY="$BODY…"
            fi

            HASH=${row:0:7}
            COMMIT_URL="https://github.com/$REPO/commit/$row"
            AUTHOR=$(jq -r ".[] | select(.id | startswith(\"$row\")) | .author.username // .author.name" <<< "$COMMITS_JSON")
            AUTHOR_URL="https://github.com/$AUTHOR"

            VALUE="[`${HASH}`]($COMMIT_URL) $TITLE — [${AUTHOR}]($AUTHOR_URL)"
            if [ -n "$BODY" ]; then
              VALUE="$VALUE\n$BODY"
            fi

            COMMITS_FIELDS=$(jq --arg name "Commit #$COUNT" --arg value "$VALUE" '. + [{name: $name, value: $value, inline: false}]' <<< "$COMMITS_FIELDS")

            if [ $COUNT -ge $MAX_COMMITS ]; then
              break
            fi
          done

          if [ $TOTAL -gt $MAX_COMMITS ]; then
            COMMITS_FIELDS=$(jq --arg url "$COMPARE" '. + [{name: "More", value: ("…and more commits, see [compare](" + $url + ")"), inline: false}]' <<< "$COMMITS_FIELDS")
          fi

          BRANCH_URL="https://github.com/$REPO/tree/$REF"
          PUSHER_URL="https://github.com/$ACTOR"
          PUSHER_AVATAR="https://github.com/$ACTOR.png"

          EMBEDS=$(jq -nc --arg repo "$REPO" --arg ref "$REF" --arg branch_url "$BRANCH_URL" --arg pusher "$ACTOR" --arg pusher_url "$PUSHER_URL" --arg pusher_avatar "$PUSHER_AVATAR" --argjson fields "$COMMITS_FIELDS" '[
            {
              author: { name: $pusher, url: $pusher_url, icon_url: $pusher_avatar },
              title: ($repo + " [" + ($fields | length | tostring) + " new commits]"),
              url: $branch_url,
              description: ("Branch: [" + $ref + "](" + $branch_url + ")"),
              color: 3066993,
              fields: $fields
            }
          ]')

          jq -nc --argjson embeds "$EMBEDS" '{username:"GitHub", avatar_url:"https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png", embeds:$embeds}' > push_payload.json

      - name: Send Push Embed
        run: |
          curl -X POST -H "Content-Type: application/json" -d @push_payload.json https://discord.com/api/webhooks/${{ secrets.DISCORD_MAIN_ID }}/${{ secrets.DISCORD_MAIN_TOKEN }}

  pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Build PR Embed
        run: |
          EVENT_JSON="${GITHUB_EVENT_PATH}"
          REPO=$(jq -r '.repository.full_name' $EVENT_JSON)
          TITLE=$(jq -r '.pull_request.title' $EVENT_JSON)
          BODY=$(jq -r '.pull_request.body // "No description"' $EVENT_JSON | cut -c1-500)
          NUMBER=$(jq -r '.pull_request.number' $EVENT_JSON)
          ACTION=$(jq -r '.action' $EVENT_JSON)
          AUTHOR=$(jq -r '.pull_request.user.login' $EVENT_JSON)
          AVATAR="https://github.com/$AUTHOR.png"
          AUTHOR_URL="https://github.com/$AUTHOR"
          HTML=$(jq -r '.pull_request.html_url' $EVENT_JSON)

          EMBEDS=$(jq -nc --arg repo "$REPO" --arg title "$TITLE" --arg body "$BODY" --arg number "$NUMBER" --arg action "$ACTION" --arg author "$AUTHOR" --arg author_url "$AUTHOR_URL" --arg avatar "$AVATAR" --arg html "$HTML" '[
            {
              author: { name: $author, url: $author_url, icon_url: $avatar },
              title: ("PR #" + $number + " " + $title),
              url: $html,
              description: ("**" + $action + "**\n\n" + $body),
              color: 3447003
            }
          ]')

          jq -nc --argjson embeds "$EMBEDS" '{username:"GitHub", avatar_url:"https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png", embeds:$embeds}' > pr_payload.json

      - name: Send PR Embed
        run: |
          curl -X POST -H "Content-Type: application/json" -d @pr_payload.json https://discord.com/api/webhooks/${{ secrets.DISCORD_PR_ID }}/${{ secrets.DISCORD_PR_TOKEN }}

  issue:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    steps:
      - name: Build Issue Embed
        run: |
          EVENT_JSON="${GITHUB_EVENT_PATH}"
          TITLE=$(jq -r '.issue.title' $EVENT_JSON)
          BODY=$(jq -r '.issue.body // "No description"' $EVENT_JSON | cut -c1-500)
          NUMBER=$(jq -r '.issue.number' $EVENT_JSON)
          ACTION=$(jq -r '.action' $EVENT_JSON)
          AUTHOR=$(jq -r '.issue.user.login' $EVENT_JSON)
          AVATAR="https://github.com/$AUTHOR.png"
          AUTHOR_URL="https://github.com/$AUTHOR"
          HTML=$(jq -r '.issue.html_url' $EVENT_JSON)

          EMBEDS=$(jq -nc --arg title "$TITLE" --arg body "$BODY" --arg number "$NUMBER" --arg action "$ACTION" --arg author "$AUTHOR" --arg author_url "$AUTHOR_URL" --arg avatar "$AVATAR" --arg html "$HTML" '[
            {
              author: { name: $author, url: $author_url, icon_url: $avatar },
              title: ("Issue #" + $number + " " + $title),
              url: $html,
              description: ("**" + $action + "**\n\n" + $body),
              color: 15158332
            }
          ]')

          jq -nc --argjson embeds "$EMBEDS" '{username:"GitHub", avatar_url:"https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png", embeds:$embeds}' > issue_payload.json

      - name: Send Issue Embed
        run: |
          curl -X POST -H "Content-Type: application/json" -d @issue_payload.json https://discord.com/api/webhooks/${{ secrets.DISCORD_ISSUES_ID }}/${{ secrets.DISCORD_ISSUES_TOKEN }}

  issue_comment:
    if: github.event_name == 'issue_comment'
    runs-on: ubuntu-latest
    steps:
      - name: Build Issue Comment Embed
        run: |
          EVENT_JSON="${GITHUB_EVENT_PATH}"
          TITLE=$(jq -r '.issue.title' $EVENT_JSON)
          NUMBER=$(jq -r '.issue.number' $EVENT_JSON)
          AUTHOR=$(jq -r '.comment.user.login' $EVENT_JSON)
          AVATAR="https://github.com/$AUTHOR.png"
          AUTHOR_URL="https://github.com/$AUTHOR"
          BODY=$(jq -r '.comment.body' $EVENT_JSON | cut -c1-500)
          HTML=$(jq -r '.comment.html_url' $EVENT_JSON)

          EMBEDS=$(jq -nc --arg title "$TITLE" --arg number "$NUMBER" --arg author "$AUTHOR" --arg author_url "$AUTHOR_URL" --arg avatar "$AVATAR" --arg body "$BODY" --arg html "$HTML" '[
            {
              author: { name: $author, url: $author_url, icon_url: $avatar },
              title: ("Comment on Issue #" + $number + " " + $title),
              url: $html,
              description: $body,
              color: 15844367
            }
          ]')

          jq -nc --argjson embeds "$EMBEDS" '{username:"GitHub", avatar_url:"https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png", embeds:$embeds}' > comment_payload.json

      - name: Send Issue Comment Embed
        run: |
          curl -X POST -H "Content-Type: application/json" -d @comment_payload.json https://discord.com/api/webhooks/${{ secrets.DISCORD_ISSUES_ID }}/${{ secrets.DISCORD_ISSUES_TOKEN }}

  pr_review_comment:
    if: github.event_name == 'pull_request_review_comment'
    runs-on: ubuntu-latest
    steps:
      - name: Build PR Review Comment Embed
        run: |
          EVENT_JSON="${GITHUB_EVENT_PATH}"
          TITLE=$(jq -r '.pull_request.title' $EVENT_JSON)
          NUMBER=$(jq -r '.pull_request.number' $EVENT_JSON)
          AUTHOR=$(jq -r '.comment.user.login' $EVENT_JSON)
          AVATAR="https://github.com/$AUTHOR.png"
          AUTHOR_URL="https://github.com/$AUTHOR"
          BODY=$(jq -r '.comment.body' $EVENT_JSON | cut -c1-500)
          HTML=$(jq -r '.comment.html_url' $EVENT_JSON)

          EMBEDS=$(jq -nc --arg title "$TITLE" --arg number "$NUMBER" --arg author "$AUTHOR" --arg author_url "$AUTHOR_URL" --arg avatar "$AVATAR" --arg body "$BODY" --arg html "$HTML" '[
            {
              author: { name: $author, url: $author_url, icon_url: $avatar },
              title: ("Review Comment on PR #" + $number + " " + $title),
              url: $html,
              description: $body,
              color: 10181046
            }
          ]')

          jq -nc --argjson embeds "$EMBEDS" '{username:"GitHub", avatar_url:"https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png", embeds:$embeds}' > pr_comment_payload.json

      - name: Send PR Review Comment Embed
        run: |
          curl -X POST -H "Content-Type: application/json" -d @pr_comment_payload.json https://discord.com/api/webhooks/${{ secrets.DISCORD_PR_ID }}/${{ secrets.DISCORD_PR_TOKEN }}

  star:
    if: github.event_name == 'watch'
    runs-on: ubuntu-latest
    steps:
      - name: Build Star Embed
        run: |
          EVENT_JSON="${GITHUB_EVENT_PATH}"
          REPO=$(jq -r '.repository.full_name' $EVENT_JSON)
          AUTHOR=$(jq -r '.sender.login' $EVENT_JSON)
          AVATAR="https://github.com/$AUTHOR.png"
          AUTHOR_URL="https://github.com/$AUTHOR"
          URL=$(jq -r '.repository.html_url' $EVENT_JSON)

          EMBEDS=$(jq -nc --arg repo "$REPO" --arg author "$AUTHOR" --arg author_url "$AUTHOR_URL" --arg avatar "$AVATAR" --arg url "$URL" '[
            {
              author: { name: $author, url: $author_url, icon_url: $avatar },
              title: "Starred Repository",
              url: $URL,
              description: ("[" + $author + "](" + $author_url + ") starred [" + $repo + "](" + $URL + ")"),
              color: 1752220
            }
          ]')

          jq -nc --argjson embeds "$EMBEDS" '{username:"GitHub", avatar_url:"https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png", embeds:$embeds}' > star_payload.json

      - name: Send Star Embed
        run: |
          curl -X POST -H "Content-Type: application/json" -d @star_payload.json https://discord.com/api/webhooks/${{ secrets.DISCORD_MAIN_ID }}/${{ secrets.DISCORD_MAIN_TOKEN }}

  fork:
    if: github.event_name == 'fork'
    runs-on: ubuntu-latest
    steps:
      - name: Build Fork Embed
        run: |
          EVENT_JSON="${GITHUB_EVENT_PATH}"
          REPO=$(jq -r '.repository.full_name' $EVENT_JSON)
          AUTHOR=$(jq -r '.sender.login' $EVENT_JSON)
          AVATAR="https://github.com/$AUTHOR.png"
          AUTHOR_URL="https://github.com/$AUTHOR"
          FORK_URL=$(jq -r '.forkee.html_url' $EVENT_JSON)

          EMBEDS=$(jq -nc --arg repo "$REPO" --arg author "$AUTHOR" --arg author_url "$AUTHOR_URL" --arg avatar "$AVATAR" --arg fork "$FORK_URL" '[
            {
              author: { name: $author, url: $author_url, icon_url: $avatar },
              title: "Forked Repository",
              url: $fork,
              description: ("[" + $author + "](" + $author_url + ") forked [" + $repo + "] to [" + $fork + "](" + $fork + ")"),
              color: 15105570
            }
          ]')

          jq -nc --argjson embeds "$EMBEDS" '{username:"GitHub", avatar_url:"https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png", embeds:$embeds}' > fork_payload.json

      - name: Send Fork Embed
        run: |
          curl -X POST -H "Content-Type: application/json" -d @fork_payload.json https://discord.com/api/webhooks/${{ secrets.DISCORD_MAIN_ID }}/${{ secrets.DISCORD_MAIN_TOKEN }}
