name: Repository Notifications

on:
  push:
    branches: ["**"]
  pull_request:
    types: [opened, closed, reopened, merged]
  issues:
    types: [opened, closed, reopened]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  watch:
    types: [started]
  fork:

jobs:
  push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Format commit list
        id: commits
        run: |
          echo "COMMITS<<EOF" >> $GITHUB_ENV
          jq -r '.[] | "- " + .id[0:7] + " " + (.message | gsub("`"; "\\`")) + " (" + .author.name + ")"' <<< '${{ toJson(github.event.commits) }}' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Send push notification
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d "{\"content\": \"**Push to \`${{ github.repository }}\`**\nBranch: \`${{ github.ref_name }}\`\nPusher: \`${{ github.actor }}\`\n\nCommits:\n${{ env.COMMITS }}\n\nRepository: https://github.com/${{ github.repository }}\nCompare: ${{ github.event.compare }}\"}" \
            https://discord.com/api/webhooks/${{ secrets.DISCORD_MAIN_ID }}/${{ secrets.DISCORD_MAIN_TOKEN }}

  pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Send PR notification
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d "{\"content\": \"**Pull Request ${{ github.event.action }}**\nRepository: \`${{ github.repository }}\`\nPR: #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}\nAuthor: \`${{ github.event.pull_request.user.login }}\`\nURL: ${{ github.event.pull_request.html_url }}\n\nDescription:\n> ${{ github.event.pull_request.body || 'No description' }}\"}" \
            https://discord.com/api/webhooks/${{ secrets.DISCORD_PR_ID }}/${{ secrets.DISCORD_PR_TOKEN }}

  issue:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    steps:
      - name: Send Issue notification
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d "{\"content\": \"**Issue ${{ github.event.action }}**\nRepository: \`${{ github.repository }}\`\nIssue: #${{ github.event.issue.number }} ${{ github.event.issue.title }}\nAuthor: \`${{ github.event.issue.user.login }}\`\nURL: ${{ github.event.issue.html_url }}\n\nDescription:\n> ${{ github.event.issue.body || 'No description' }}\"}" \
            https://discord.com/api/webhooks/${{ secrets.DISCORD_ISSUES_ID }}/${{ secrets.DISCORD_ISSUES_TOKEN }}

  issue_comment:
    if: github.event_name == 'issue_comment'
    runs-on: ubuntu-latest
    steps:
      - name: Send Issue/PR comment notification
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d "{\"content\": \"**New Comment**\nRepository: \`${{ github.repository }}\`\nOn: #${{ github.event.issue.number }} ${{ github.event.issue.title }}\nAuthor: \`${{ github.event.comment.user.login }}\`\nURL: ${{ github.event.comment.html_url }}\n\nComment:\n> ${{ github.event.comment.body }}\"}" \
            https://discord.com/api/webhooks/${{ secrets.DISCORD_ISSUES_ID }}/${{ secrets.DISCORD_ISSUES_TOKEN }}

  pr_review_comment:
    if: github.event_name == 'pull_request_review_comment'
    runs-on: ubuntu-latest
    steps:
      - name: Send PR review comment notification
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d "{\"content\": \"**New Review Comment**\nRepository: \`${{ github.repository }}\`\nPR: #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}\nAuthor: \`${{ github.event.comment.user.login }}\`\nURL: ${{ github.event.comment.html_url }}\n\nComment:\n> ${{ github.event.comment.body }}\"}" \
            https://discord.com/api/webhooks/${{ secrets.DISCORD_PR_ID }}/${{ secrets.DISCORD_PR_TOKEN }}

  star:
    if: github.event_name == 'watch'
    runs-on: ubuntu-latest
    steps:
      - name: Send Star notification
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d "{\"content\": \"**New Star**\nRepository: \`${{ github.repository }}\`\nUser: \`${{ github.actor }}\`\nRepository URL: https://github.com/${{ github.repository }}\"}" \
            https://discord.com/api/webhooks/${{ secrets.DISCORD_MAIN_ID }}/${{ secrets.DISCORD_MAIN_TOKEN }}

  fork:
    if: github.event_name == 'fork'
    runs-on: ubuntu-latest
    steps:
      - name: Send Fork notification
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d "{\"content\": \"**New Fork**\nRepository: \`${{ github.repository }}\`\nUser: \`${{ github.actor }}\`\nForked To: https://github.com/${{ github.actor }}/$(basename ${{ github.repository }})\"}" \
            https://discord.com/api/webhooks/${{ secrets.DISCORD_MAIN_ID }}/${{ secrets.DISCORD_MAIN_TOKEN }}
